parameters:
  upload_dir: '../var/uploads'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, ...

    bind:
      $uploadDir: '%upload_dir%/public/'